# Generated by Django 2.0.3 on 2018-09-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('companyaddress', models.CharField(max_length=100)),
                ('companybusiness', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisorname', models.CharField(max_length=100)),
                ('supervisorcompanyid', models.CharField(max_length=100)),
                ('supervisorusername', models.CharField(max_length=100)),
                ('supervisorpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
