# Generated by Django 2.0.3 on 2018-09-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidd', '0002_company_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='lastname',
            new_name='password',
        ),
    ]
